#Service defination :Nodeport opens a port on the cluster while Loadbalancer provides a unique public URI/IP
apiVersion: v1
kind: Service
metadata:
  labels:
    run: myapp-service
  name: myapp-service
  namespace: prod
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
    protocol: TCP
  selector:
    app: myapp-service
  type: LoadBalancer


#Deployment defination: Contains details of the repricas we want, the image version volume mounts and registry secrets
---
apiVersion: v1
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: myapp-deployment
    version: prod
  name: myapp-deployment
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-service
      version: prod
  template:
    metadata:
      labels:
        app: myapp-service
        version: prod
    spec:
      containers:
      - image: bwn100/mywebsite:v1
        name: myapp-service
        ports:
        - containerPort: 80
